### ISSUE TITLE
how to set barcode formats? 

### ISSUE THREAD

**Issue by jodaka** [rusfearuth/zxing-lib-extended#3]
It seems that scanner only scans QRCodes, but I need to be able to scans products barcodes (like this one http://www.barcode1.in/wp-content/uploads/ISSN.jpg )

I couldn't figure out how to specify formats. Any help highly appreciated

**Comment by rusfearuth** [comment]
It scans different formates.

For instance,

@Override
        public void handleBarcode(Result result, Bitmap arg1, float arg2) {
            Toast.makeText(HelloAndroidActivity.this, result.getText(), Toast.LENGTH_LONG).show();
            xf.restartScanningIn(200);
        }

result contains information about format. Could you checkout result output and write it here?

**Comment by jodaka** [comment]
At first I tried using original ZXing and after much struggling with integration into my app, it does scanned different formats. Though there was no portrait mode, so I decided to try this lib. 

When I'm trying to scan a barcode on the product nothing happens. No callback gets fired. That red line keeps blinking for ever. I was able to scan exactly the same barcode almost instantly with original zxing. 

And this lib seems to react only on QRcodes.

**Comment by rusfearuth** [comment]
You're wrong about "And this lib seems to react only on QRcodes". Could I get more information about you code?

**Comment by rusfearuth** [comment]
I don't know how to you connect this library, but in my test app everything is fine. 

http://dl.dropbox.com/u/10179307/%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_007.bmp

**Comment by jodaka** [comment]
Could you maybe post your test app on github so I could compare and see what am I doing wrong?

**Comment by rusfearuth** [comment]
@jodaka okay, but I see that problem from your side.

**Comment by jodaka** [comment]
Yep, I'm pretty sure the problem is somewhere in my code, but I can't figure out where exactly. And since it's not my personal project, I can't just share code :(

**Comment by rusfearuth** [comment]
https://gist.github.com/rusfearuth/d064ea6eb0b5497285a5

**Comment by rusfearuth** [comment]
@jodaka Did library return any barcode? Probably, bug is in adding callback.
